name: CI/CD Pipeline

on:
  push:
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_unix.txt

      - name: Run unit tests
        run: |
          echo "Running unit tests"
          python -m unittest discover tests/unit/

      - name: Start Flask application
        run: |
          python src/app.py &

      - name: Run integration tests with Selenium
        run: |
          echo "Running integration tests"
          python -m unittest discover tests/integration/

  merge-to-main:
    needs: test
    if: github.ref == 'refs/heads/staging' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Actions"

      - name: Checkout main branch
        run: git checkout main

      - name: Fetch the dev branch
        run: git fetch origin dev:dev

      - name: Merge Dev into Main
        run: |
          git merge dev --no-ff -m "Merge dev into main"
          git push https://${{ secrets.CESAR_PAT }}@github.com/MLOPS-Training/mlops_app.git main

  deploy:
    needs: merge-to-main
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: cesarombredane/mlops_app

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
