name: Run Tests

on:
  push:
    branches:
      - staging
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_unix.txt

      - name: Run unit tests
        run: |
          echo "Running unit tests"
          python -m unittest discover tests/unit/

      - name: Start Flask application
        run: |
          python src/app.py &

      - name: Run integration tests with Selenium
        run: |
          echo "Running integration tests"
          python -m unittest discover tests/integration/
